{
 "title": "ODIS-sieć",
 "time": { "from": "2019-06-03T19:46:44.631Z", "to": "2019-06-03T19:47:01.720Z" },
 "panels": [
  {
   "title": "Ruch na jak dojade",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(that_time),\n  bytes,\n  rule_name\nFROM logs where rule_name = ('JakDojade');"
    }
   ]
  },
  {
   "title": "Ruch na stronach",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(that_time),\n  bytes,\n  rule_name\nFROM logs where rule_name not in ('Incoming Total System','Outgoing Total System') ;\n"
    }
   ]
  },
  {
   "title": "Globalny ruch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(that_time),\n  bytes,\n  rule_name\nFROM logs where rule_name  in ('Incoming Total System','Outgoing Total System') ;\n"
    }
   ]
  },
  {
   "title": "Zestaawienie ruchu",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "rawSql": "SELECT *\nfrom logs;" }
   ]
  }
 ]
}